
// 8 sprites generated with spritemate on 3/23/2022, 9:50:51 PM
// Byte 64 of each sprite contains multicolor (high nibble) & color (low nibble) information


// sprite 7 / singlecolor / color: $0c
.byte $3f,$fc,$00,$7f,$fe,$00,$ff,$ff
.byte $00,$ff,$ff,$00,$ff,$ff,$00,$ff
.byte $ff,$00,$ff,$ff,$00,$ff,$ff,$00
.byte $ff,$ff,$00,$ff,$ff,$00,$ff,$ff
.byte $00,$ff,$ff,$00,$ff,$ff,$00,$ff
.byte $ff,$00,$7f,$fe,$00,$3f,$fc,$00
.byte $00,$00,$00,$00,$00,$00,$00,$00
.byte $00,$00,$00,$00,$00,$00,$00,$0c
